# Win2Linux Unattended Kickstart Configuration for Fedora Workstation 44
# Generated by Win2Linux Dual-Boot Installer
# Install method: Network (netinstall) — packages are fetched from Fedora mirrors

# System language & keyboard
lang en_US.UTF-8
keyboard us
timezone UTC --utc

# Network configuration (required for netinstall package fetch)
network --bootproto=dhcp --device=link --activate --hostname=fedora-dualboot

# Package installation source (netinstall repo)
url --mirrorlist=https://mirrors.fedoraproject.org/mirrorlist?repo=fedora-44&arch=x86_64

# Firewall & SELinux
firewall --enabled --service=ssh
selinux --enforcing

# Root password and initial user
rootpw --lock
user --name=user --plaintext --password=changeme --groups=wheel

# Bootloader configuration (Signed Secure Boot shim)
bootloader --location=none

# Automated partitioning into unallocated free space only
# NEVER clear existing partitions on secondary or system disks
clearpart --none
autopart --type=btrfs --nohome

# Package selection
%packages
@core
@workstation-product-environment
efibootmgr
shim-x64
grub2-efi-x64
os-prober
ntfs-3g
%end

# Post-install dual-boot GRUB configuration
%post
# Enable OS prober so GRUB detects Windows Boot Manager
echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg
%end

reboot
